<?php

namespace api\modules\v1\models;

use common\models\User as US;

class User extends US
{

    const SCENARIO_CHANGE_PASS='change-pass';
    public $password;
    public $new_password;

    public function rules()
    {
        $rules=parent::rules(); // TODO: Change the autogenerated stub
        $rules[]=['email','required'];
        $rules[]=['email','email'];
        $rules[]=['email','unique'];
        $rules[]=['password','required'];
        $rules[]=['new_password','required','on'=>self::SCENARIO_CHANGE_PASS];
        return $rules;
    }

    public function beforeSave($insert)
    {
        if(parent::beforeSave($insert)){
            if($insert){
                $this->setPassword($this->password);
                $this->generateAuthKey();
                $this->generateEmailVerificationToken();
                $this->status=10;
                $this->username=$this->email;
            }
            return true;
        } // TODO: Change the autogenerated stub
        return false;
    }

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        unset($fields['username'], $fields['password_hash'] , $fields['password_reset_token'] , $fields['verification_token'] ,
            $fields['status']);
        return $fields;
    }
}